insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (7579, 'Rempel-Dach', 'Veal - Brisket, Provimi, Bone - In', 18, 76, 'Clothing', 8);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (6521, 'Becker LLC', 'Sherbet - Raspberry', 76, 40, 'Outdoors', 7);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (9659, 'Senger, Wolf and Mueller', 'Muffin Hinge - 211n', 100, 84, 'Grocery', 6);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (1433, 'Schinner-Renner', 'Appetizer - Tarragon Chicken', 16, 68, 'Sports', 8);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (3972, 'Sipes LLC', 'Tray - Foam, Square 4 - S', 54, 74, 'Toys', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (5281, 'Kunze and Sons', 'Asparagus - Mexican', 9, 97, 'Automotive', 5);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (2310, 'Mosciski-Connelly', 'Flour - Masa De Harina Mexican', 21, 44, 'Movies', 8);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (2459, 'Swift, Herman and Walker', 'Foam Dinner Plate', 7, 42, 'Clothing', 5);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (8741, 'Kulas, Terry and Senger', 'Pepper - Scotch Bonnet', 91, 49, 'Industrial', 9);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (2886, 'West and Sons', 'Nantucket - Carrot Orange', 65, 56, 'Shoes', 6);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (8631, 'Carter, Koch and Crona', 'Syrup - Monin - Passion Fruit', 54, 70, 'Kids', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (6927, 'Romaguera, Prohaska and Spinka', 'Chocolate - Semi Sweet, Calets', 90, 42, 'Health', 8);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (8275, 'Toy Inc', 'Cake - Sheet Strawberry', 33, 98, 'Automotive', 8);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (1119, 'Stoltenberg Group', 'Bok Choy - Baby', 21, 76, 'Games', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (3994, 'Smitham, Hackett and Runolfsdottir', 'Cookies - Englishbay Chochip', 84, 32, 'Jewelry', 6);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (7301, 'Macejkovic, Lang and Streich', 'Chicken Thigh - Bone Out', 27, 72, 'Kids', 5);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (3843, 'Becker, Mosciski and Satterfield', 'Soup - Campbells, Classic Chix', 78, 67, 'Industrial', 7);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (5478, 'Shanahan Inc', 'Duck - Whole', 2, 70, 'Electronics', 5);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (6339, 'Waelchi Inc', 'Pasta - Gnocchi, Potato', 30, 41, 'Baby', 6);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (3811, 'Rice, Mitchell and Champlin', 'Brandy Apricot', 3, 67, 'Shoes', 6);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (1182, 'Stroman LLC', 'Soup - Campbells', 80, 34, 'Electronics', 7);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (1776, 'Hilpert, Herman and Hackett', 'Jicama', 89, 50, 'Baby', 6);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (9520, 'Casper-Glover', 'Wine - Taylors Reserve', 81, 63, 'Electronics', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (1054, 'Muller-Bruen', 'Jolt Cola - Electric Blue', 16, 64, 'Beauty', 5);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (3088, 'Schaden-Ullrich', 'Steel Wool', 8, 31, 'Grocery', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (7382, 'Cummerata Inc', 'Pasta - Shells, Medium, Dry', 76, 37, 'Toys', 5);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (9999, 'Terry-Smith', 'Scallops - U - 10', 66, 49, 'Health', 9);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (1338, 'Maggio, Dietrich and Will', 'Soup - Canadian Pea, Dry Mix', 23, 48, 'Books', 5);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (2054, 'Schinner-Schneider', 'Pork - Side Ribs', 77, 46, 'Movies', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (1094, 'Tremblay, Macejkovic and Daniel', 'The Pop Shoppe Pinapple', 92, 96, 'Clothing', 6);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (9231, 'Ward, Turcotte and Stokes', 'Chocolate - Semi Sweet', 24, 54, 'Clothing', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (5405, 'Weimann, Davis and Marks', 'Passion Fruit', 28, 62, 'Books', 7);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (5906, 'Jenkins, Stark and Lubowitz', 'Water - Green Tea Refresher', 32, 37, 'Outdoors', null);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (7253, 'Tillman Group', 'Cheese - Manchego, Spanish', 34, 68, 'Home', 9);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (2874, 'Witting, Gutmann and O''Conner', 'Celery', 38, 31, 'Computers', 5);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (3437, 'Lind Inc', 'Scallops - U - 10', 43, 81, 'Outdoors', 7);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (9353, 'Goldner Inc', 'Quinoa', 4, 77, 'Sports', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (3901, 'Cartwright Group', 'Wine - Cahors Ac 2000, Clos', 23, 58, 'Shoes', 6);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (1114, 'Donnelly, Wilderman and Boyer', 'Arizona - Plum Green Tea', 62, 100, 'Beauty', 8);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (9559, 'Hammes and Sons', 'Parsnip', 53, 52, 'Kids', 9);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (6527, 'Goyette-Wyman', 'Beef - Bones, Marrow', 18, 39, 'Home', 8);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (7203, 'Maggio and Sons', 'Salt - Kosher', 11, 87, 'Baby', 8);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (2941, 'Hammes Inc', 'Sea Bass - Whole', 70, 64, 'Movies', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (3077, 'Christiansen LLC', 'Lamb - Loin Chops', 24, 48, 'Baby', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (2338, 'Morissette-Bartell', 'Beer - Molson Excel', 4, 100, 'Clothing', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (9437, 'Erdman, Kuphal and Bartoletti', 'Pork Casing', 13, 52, 'Books', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (5980, 'Lindgren-Schumm', 'Soup - Base Broth Chix', 19, 87, 'Kids', 9);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (6096, 'Parisian, Stroman and McCullough', 'Veal - Striploin', 28, 66, 'Games', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (2137, 'Vandervort-Lang', 'Orange - Canned, Mandarin', 56, 46, 'Clothing', 10);
insert into inventory (item_id, company_name, item_name, qty, price, category, discount) values (9457, 'Smith and Sons', 'Truffle Cups Green', 23, 83, 'Clothing', 6);
